### PR TITLE
Apply SSL/TLS options in fetching nextUri

### PR DESCRIPTION
**Pull request by tagomoris**
This is an alternative approach as the solution of #33, by applying SSL/TLS options also on fetching nextUri by single String argument.

This change also contains the fix for code styles and others to make further maintenance easier.

### CODE REVIEW

**Comment by souryabharath** [comment]
The changes resolved the redirect issue. Let me know if you want me to approve this PR.

**Comment by tagomoris** [comment]
@souryabharath your comment is great enough. Thank you very much!

**Comment by tagomoris** [comment]
Shipped 0.8.0 https://www.npmjs.com/package/presto-client/v/0.8.0

**Comment by souryabharath** [comment]
Thank you very much for fixing it. Really appreciate it.

**Pull request merged**
