### PR TITLE
Support HTTPS

### PR DESCRIPTION
**Pull request by kwent**
### Support HTTPS

Add `https` support.

Related to: https://github.com/tagomoris/presto-client-node/issues/13

### CODE REVIEW

**Comment by martin-kieliszek** [comment]
I'm curious to know whether more people are similar to kwent and myself - hoping to obtain https support?

**Comment by tagomoris** [comment]
Thank you for the patch! I'm so sorry to miss this long time.

**Comment by tagomoris** [comment]
I've just shipped `v0.2.0`.

**Comment by kwent** [comment]
Thanks ! You should also update this [section](https://github.com/tagomoris/presto-client-node#versions) in `README.md`. 👍

**Comment by tagomoris** [comment]
Oops! I've done it!
@kwent Thank you!

**Comment by martin-kieliszek** [comment]
My business requirements forced me to implement Basic Authorization on all requests (including nextUri requests). May either of you peer review the following suggestion?
[#18](https://github.com/tagomoris/presto-client-node/issues/18)

Currently working on my local machine albeit in a very specific use-case. No exceptions yet.

**Pull request merged**
